port: 50000
log:
  output: file
  filePath: logs/app.log
  level: info # level: info # logrus Level: error, warning, info, debug, trace
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  name: epaygates_dev
  maxOpenConnections: 200
  maxIdleConnections: 50 # Usually 10â€“25% of MaxOpenConns
  maxLifeTimeInSeconds: 1800