metadataService:
  grpcAddress: "127.0.0.1:50000"
apiGateway:
  grpcAddress: "127.0.0.1:50500"
  httpAddress: "http://127.0.0.1:50500"
cms:
  httpAddress: "http://127.0.0.1:50501"
web:
  httpAddress: "http://127.0.0.1:50502"